name: dqnheadless
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
- cudatoolkit=10.0
- pip:
  - torchvision
  - matplotlib
  - plotly
  - torchviz
  - wandb
  - tqdm
  - gym
  - gym[atari]
  - numpy
  - opencv-python
  - pyvirtualdisplay