name: deeplearning
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
- cudatoolkit=10.0
- pip:
  - torchvision
  - matplotlib
  - seaborn
  - torchviz
  - wandb
  - scipy
  - tqdm
  - gym
  - numpy
  - pandas